### ISSUE TITLE
Random Things

### ISSUE THREAD

**Issue by pikaninja** [PB4162/PB-Bot#16]
[here](https://github.com/PB4162/PB-Bot/blob/master/utils/classes.py#L80) no point to get event loop twice, either store it in a var or just use `self.loop`

I would argue instead of defining the check inside the `__init__` it would be cleaner to define the check as a method and use `bot.add_check`

[here](https://github.com/PB4162/PB-Bot/blob/master/utils/classes.py#L246) any reason you're using extend and not just +=?

**Comment by PB4162** [comment]
I agree that using `get_event_loop` twice is unnecessary.
About the check, I feel that it's fine as it is.
I'm not exactly sure why I decided to use `extend` over `+=`.
